select * from zomato_orders;
select * from zomato_restaurants;

#check duplicate records

SELECT order_id,Restaurant_ID,customer_id,Order_Date, order_time, delivery_time,total_cost,item_count,payment_method,customer_rating,
COUNT(*) AS duplicate_count
FROM zomato_orders
GROUP BY Order_ID,Restaurant_ID,customer_id,Order_Date, order_time, delivery_time,total_cost,item_count,payment_method,customer_rating
HAVING COUNT(*) > 1;

SELECT Restaurant_ID, restaurant_name, city, Area,cuisine,avg_rating,total_ratings,price_range,delivery_available,
 COUNT(*) AS duplicate_count
FROM zomato_restaurants
GROUP BY restaurant_id, restaurant_name, city, Area,cuisine,avg_rating,total_ratings,price_range,delivery_available
HAVING COUNT(*) > 1;

# remove duplicate records
DELETE FROM zomato_orders 
WHERE Order_ID NOT IN (
    SELECT * FROM (
        SELECT MIN(order_id) 
        FROM zomato_orders 
        GROUP BY Restaurant_ID,customer_id,Order_Date, order_time, delivery_time,total_cost,item_count,payment_method,customer_rating
    ) as tmp_table
);
DELETE FROM zomato_restaurants
WHERE Restaurant_ID NOT IN (
    SELECT * FROM (
        SELECT MIN(order_id) 
        FROM zomato_orders 
        GROUP BY Restaurant_ID,customer_id,Order_Date, order_time, delivery_time,total_cost,item_count,payment_method,customer_rating
    ) as tmp_table
);

# handling null values(if any) by replacing them with appropriate values
select * from zomato_restaurants
where Restaurant_ID is null
or Restaurant_Name is null 
or city is null
or area is null
or cuisine is null
or avg_rating is null
or total_ratings is null
or price_range is null
or delivery_available is null;

select * from zomato_orders
where order_id is null
or customer_id is null
or Restaurant_ID is null
or order_date is null
or order_time is null
or delivery_time is null
or total_cost is null
or item_count is null
or payment_method is null
or customer_rating is null;

#count the number of restaurants in each city
select city,count(restaurant_id) as restaurant
from zomato_restaurants
group by city
order by restaurant desc;

#Top 5 cities with highest number of orders
select city, count(order_id) as orders
from zomato_restaurants join zomato_orders
group by city
order by orders desc
limit 5;

#Total revenue generated by each restaurant
select r.restaurant_name,r.Restaurant_ID,sum(o.total_cost) as total_revenue
from zomato_restaurants as r
join zomato_orders as o on r.Restaurant_ID=o.Restaurant_ID
group by r.restaurant_name,r.Restaurant_ID
order by total_revenue desc;

#average order amount for each city
select r.city, avg(o.total_cost*o.item_count) as Avg_order_amount
from zomato_restaurants as r 
join zomato_orders as o on r.restaurant_id=o.restaurant_id
group by city
order by Avg_order_amount desc;

#Top 5 restaurants with highest total sales
select r.restaurant_name,r.Restaurant_ID,count(o.order_id) as total_sales
from zomato_restaurants as r
join zomato_orders as o on r.Restaurant_ID=o.Restaurant_ID
group by r.Restaurant_Name,r.Restaurant_ID
order by total_sales desc
limit 5;

#Join the Zomato_Orders and Zomato_Restaurants tables to get restaurant names along with order details.
select o.order_id,o.restaurant_id,o.customer_id,o.order_date,o.order_time,o.delivery_time,o.total_cost,o.item_count,o.payment_method,o.customer_rating,
r.restaurant_name,r.city,r.area,r.cuisine,r.avg_rating,r.total_ratings,r.price_range,r.delivery_available
 from zomato_orders as o join zomato_restaurants as r
on r.Restaurant_ID=o.Restaurant_ID;

